geo:
  region_bias: us
  locations:
    base:
      latitude: 40.264
      longitude: -74.522
  boundaries:
    autocomplete:
      sw:
        latitude: 39.72
        longitude: -75.08
      ne:
        latitude: 40.93
        longitude: -73.84

google:
  api:
    simple:
      key: "AIzaSyB1JJByWOaoOIjf1P-sg5XvzoBBFLi8NpY"
